---
language: java

sudo: required

services:
  - docker

before_install:
  - docker pull lukasmartinelli/hadolint
  - docker run --rm -i lukasmartinelli/hadolint hadolint  - < src/main/Dockerfile
  - docker run -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/scripts/*sh

script:
  - mvn verify
  
